import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  listClip: {
    width: '100%',
    paddingTop: 4,
    paddingBottom: 68,
  },
  card: {
    width: '100%',
    height: 'auto',
    marginTop: 20,
    marginBottom: 0,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#111',
  },
  cardImage: {
    height: 260,
    justifyContent: 'flex-end',
  },
  listContent: {
    paddingBottom: 150,
  },
  cardMenu: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 4,
    zIndex: 1,
  },
  cardMenuActive: {
    backgroundColor: '#EADFD7', // square background
    borderRadius: 0,
  },
  cardTitleOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 25,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    pointerEvents: 'none',
  },
  cardMask: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(40,40,40,0.45)',
  },
  cardTitleText: {
    color: '#fff',
    fontFamily: 'AntonSC',
    fontSize: 32,
    lineHeight: 60,
    fontWeight: '400',
    letterSpacing: 1,
    textAlign: 'center',
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 3,
  },
  menuWrap: {
    position: 'absolute',
    top: 40,
    right: 8,
    backgroundColor: '#EADFD7',
    paddingVertical: 0,
    paddingHorizontal: 0,
    zIndex: 2,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
    elevation: 6,
  },
  menuBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'transparent',
    zIndex: 1,
  },
});
