import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 24,
  },
  buttonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 32,
  },
  photosRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  photoWrap: {
    position: 'relative',
  },
  photo: {
    width: 80,
    height: 80,
    borderRadius: 8,
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 16,
  },
  sectionSubtitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 24,
    marginBottom: 8,
  },
  addPhotoContainer: {
    alignItems: 'center',
    marginVertical: 24,
  },
  galleryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 32,
    gap: 16,
  },
  photosList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
    marginBottom: 24,
    justifyContent: 'flex-start',
  },
  photoCard: {
    width: '49%',
    aspectRatio: 4 / 3,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#222',
    marginBottom: 8,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 140,
  },
  photoImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  photoOverlay: {
    backgroundColor: 'rgba(0,0,0,0.25)',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  photoStep: {
    position: 'absolute',
    left: 24,
    bottom: 24,
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    opacity: 0.9,
  },
  editIcon: {
    position: 'absolute',
    right: 24,
    bottom: 24,
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderRadius: 20,
    padding: 4,
  },
  removeBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 16,
    padding: 2,
    zIndex: 2,
  },
  addPhotoCard: {
    width: '49%',
    aspectRatio: 4 / 3,
    borderRadius: 12,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F7F4F1', // stays as fallback under SVG
    marginBottom: 8,
    minHeight: 140,
    position: 'relative',
  },
  addPhotoContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1, // content above SVG bg
  },
  addPhotoText: {
    color: '#181818',
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 8,
    textAlign: 'center',
  },
  scrollView: {
    overflow: 'hidden',
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 0,
    margin: 0,
    width: '100%',
    paddingTop: 4,
    paddingBottom: 150,
  },
  contentClip: {
    width: '100%',
    paddingTop: 4,
    paddingBottom: 68,
    flex: 1,
  },
  fieldSpacing10: { marginBottom: 10 },
});
